schema_version = "1.0.0"
id = "objectdisplay"
version = "1.2.0"
name = "Mesh Display"
tagline = "Adds buttons to quickly switch between mesh display types"
maintainer = "Blender Bob"
type = "add-on"
website = "https://github.com/riouxr/Object-Display"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2024 Robert Rioux"]